---
- name: Power on VM
  hosts: localhost
  gather_facts: false
  collections:
   - community.vmware

  pre_tasks:
   - include_vars: vcenter_vars.yml

  tasks:
   - name: power on vm
     vmware_guest_powerstate:
        hostname: "{{vcenter_hostname}}"
        username: "{{vcenter_username}}"
        password: "{{vcenter_password}}"
        validate_certs: "{{vcenter_validate_certs}}"
        name: "{{vm_name}}"
        state: powered-on
