---
- name: power off vm
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware

  # vars_prompt:
  #   - name: vcenter_username
  #     prompt: "Enter vcenter username"
  #   - name: vcenter_password
  #     prompt: "Enter vcenter password"
  #     private: yes

  pre_tasks:
    - include_vars: vcenter_vars.yml

  tasks:
    - name: guest shutdown
      vmware_guest_powerstate:
         hostname: "{{vcenter_hostname}}"
         username: "{{vcenter_username}}"
         password: "{{vcenter_password}}"
         validate_certs: "{{vcenter_validate_certs}}"
         name: "{{vm_name}}"
         state: shutdown-guest
         state_change_timeout: 120
      register: shutdown
      ignore_errors: true

    - name: poweroff
      vmware_guest_powerstate:
         hostname: "{{vcenter_hostname}}"
         username: "{{vcenter_username}}"
         password: "{{vcenter_validate_certs}}"
         name: "{{vm_name}}"
         state: powered-off
      when: shutdown.failed

