- name: Install XRDP on ubuntu20 machines
  hosts: localhost

  tasks: 
    - name: Download XRDP package
      get_url:
         url: http://archive.ubuntu.com/ubuntu/pool/universe/x/xrdp/xrdp_0.9.12-1_amd64.deb
         dest: /tmp/xrdp-package.deb

- name: Install XRDP on ubuntu20 machines
  hosts: '{{host_name}}'
  become: true
  
  tasks:
    - name: Transfer package to ub20
      copy:
         src: /tmp/xrdp-package.deb
         dest: /tmp/xrdp-package.deb
    
    - name: Install xrdp package
      apt:
         deb: /tmp/xrdp-package.deb