---
- name: Power on VM
  hosts: localhost
  gather_facts: false
  collections:
   - community.vmware

  vars_prompt:
   - name: username
     prompt: "Enter Username"
   - name: password
     prompt: "Enter Password"
     private: yes

  pre_tasks:
   - include_vars: vcenter_vars.yml

  tasks:
   - name: power on vm
     vmware_guest_powerstate:
        hostname: "{{vcenter_hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: "{{vcenter_validate_certs}}"
        name: "{{vm_name}}"
        state: powered-on
